version: "3.9"

services:
  backend:
    image: mcr.microsoft.com/playwright:v1.49.0-noble
    platform: linux/amd64
    restart: unless-stopped
    volumes:
        - ./:/usr/src/web/
    command: bash -c "cd /usr/src/web/ && npm run start"