version: "3.9"

services:
  backend:
    image: mcr.microsoft.com/playwright:latest
    volumes:
        - ./:/usr/src/web/
    ports:
      - 8000:8000
    working_dir: /usr/src/web/
    command: node ./dist/index.js