version: "3.9"

services:
  backend:
    image: mcr.microsoft.com/playwright:v1.49.0-noble
    restart: unless-stopped
    volumes:
        - ./:/usr/src/web/
    command: node /usr/src/web/dist/index.js